#!/bin/sh

set -e

# Don't bother to restart sshd when lo is configured.
if [ "$IFACE" = lo ]; then
	exit 0
fi

# Only run from ifup.
if [ "$MODE" != start ]; then
	exit 0
fi

# OpenSSH only cares about inet and inet6. Get ye gone, strange people
# still using ipx.
if [ "$ADDRFAM" != inet ] && [ "$ADDRFAM" != inet6 ]; then
	exit 0
fi

if [ -f /var/run/apcupsd.pid ]; then
	exit 0
fi

if [ -x /usr/sbin/service ]; then
	service apcupsd start
fi

exit 0

